In [ ]:
import numpy as np
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
(~((output > 0) & (output <= 1)))

array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [ ]:
a = np.array(range(1, 30))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(a)
a[1:3,0:2]
a[[1,2]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
a = np.array([1, 2, 3], dtype="float")
print(a)

# a.ndim
# a.shape
a.itemsize

[1. 2. 3.]


8

In [ ]:
# indexing
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(x)
x[1, 2] = 12
print(x)

x[1:3, 0:2]

x[[0,1,3],3:]

x[[0,1,2,3],[0,1,2,3]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7 12  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 1,  7, 13, 19])

In [ ]:
# indexing
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(x)
# x[1, 2] = 12
# print(x)

# x[1:3, 0:2]
print()
x[[0,1,3],3:]

# x[[0,1,2,3],[1,2,3,4]]

# [2, 3], [7, 8], [13, 14], [18, 19]

np.concatenate((x[0:2, 1:3], x[2:4, 2:4]))
# x[[0, 1], [1, 2]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



array([[ 2,  3],
       [ 7,  8],
       [13, 14],
       [18, 19]])

In [ ]:
# indexing
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(x)
# x[1, 2] = 12
# print(x)
print()
print(x[[0,1,2,3],[1,2,3,4]])
print()
print(x[0:,[1,2,3,4]])

# [2, 3], [7, 8], [13, 14], [18, 19]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 2  8 14 20]

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
